export const holidays2026 = [
    { SNo: 1, Festival: "Republic Day", Date: "26th January 2026", Day: "Monday" },
    { SNo: 2, Festival: "Maha Shivratri", Date: "15th February 2026", Day: "Sunday" },
    { SNo: 3, Festival: "Holika Dahan", Date: "2nd March 2026", Day: "Monday" },
    { SNo: 4, Festival: "Holi", Date: "4th March 2026", Day: "Wednesday" },
    { SNo: 5, Festival: "Id-Ul-Fittar", Date: "21st March 2026", Day: "Saturday" },
    { SNo: 6, Festival: "Ram Navmi", Date: "26th March 2026", Day: "Thursday" },
    { SNo: 7, Festival: "Mahaveer Jayanti", Date: "31st March 2026", Day: "Tuesday" },
    { SNo: 8, Festival: "Dr. Bhimrao Ambedkar's Birthday", Date: "14th April 2026", Day: "Tuesday" },
    { SNo: 9, Festival: "Budh Purnima", Date: "1st May 2026", Day: "Friday" },
    { SNo: 10, Festival: "Ed-Ul-Juha (Bakreed)", Date: "27th May 2026", Day: "Wednesday" },
    { SNo: 11, Festival: "Moharrum", Date: "26th June 2026", Day: "Friday" },
    { SNo: 12, Festival: "Independence Day", Date: "15th August 2026", Day: "Saturday" },
    { SNo: 13, Festival: "Raksha Bandhan", Date: "28th August 2026", Day: "Friday" },
    { SNo: 14, Festival: "Janmashtami", Date: "4th September 2026", Day: "Friday" },
    { SNo: 15, Festival: "Mahatma Gandhi Jayanti", Date: "2nd October 2026", Day: "Friday" },
    { SNo: 16, Festival: "Dussehara (Maha Navmi) / Vijay Dashmi", Date: "20th October 2026", Day: "Tuesday" },
    { SNo: 17, Festival: "Deepawali / Narak Chaturdashi", Date: "8th November 2026", Day: "Sunday" },
    { SNo: 18, Festival: "Goverdhan Puja", Date: "9th November 2026", Day: "Monday" },
    { SNo: 19, Festival: "Bhai Duj / Chitragupt Jayanti", Date: "11th November 2026", Day: "Wednesday" },
    { SNo: 20, Festival: "Guru Nanak Jayanti / Kartik Purnima / Guru Teg Bahadur Shaheed Diwas", Date: "24th November 2026", Day: "Tuesday" },
    { SNo: 21, Festival: "Christmas Day", Date: "25th December 2026", Day: "Friday" }
];